package orderbook;

import org.openjdk.jmh.annotations.*;

import java.util.Random;
import java.util.concurrent.TimeUnit;

/**
 * Steady-state benchmarks (ADR-0037): every invocation leaves the book the same size, so the
 * measurement never degenerates into an empty or ever-growing book.
 *
 * <p>Order objects are allocated inside the measured call because the engine consumes the
 * object it is given; that cost is part of every figure.
 *
 * <p>Run (after {@code mvn test-compile}):
 * {@code java -cp target/test-classes:target/classes:<test classpath> org.openjdk.jmh.Main}
 */
@BenchmarkMode({Mode.Throughput, Mode.SampleTime})
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Warmup(iterations = 3, time = 1)
@Measurement(iterations = 5, time = 2)
@Fork(2)
public class MatchingEngineBenchmark {

    private static final int DEEP_LEVEL_ORDERS = 10_000;
    private static final int STREAM_LENGTH = 1 << 17;           // 131072 pre-generated operations

    @State(Scope.Thread)
    public static class SmallBook {
        OrderBook orderBook;
        MatchingEngine engine;
        long nextId;

        @Setup(Level.Iteration)
        public void setup() {
            orderBook = new OrderBook();
            engine = new MatchingEngine(orderBook);
            nextId = 1;

            // some resting liquidity on both sides so best-price lookups are not trivial
            for (int i = 0; i < 20; i++) {
                engine.processOrder(new LimitOrder(nextId++, Side.BUY, 100, 1_000 - i));
                engine.processOrder(new LimitOrder(nextId++, Side.SELL, 100, 2_000 + i));
            }
        }
    }

    @State(Scope.Thread)
    public static class DeepLevel {
        OrderBook orderBook;
        MatchingEngine engine;
        int cursor;

        @Setup(Level.Iteration)
        public void setup() {
            orderBook = new OrderBook();
            engine = new MatchingEngine(orderBook);
            cursor = 0;

            for (int i = 0; i < DEEP_LEVEL_ORDERS; i++) {
                engine.processOrder(new LimitOrder(i, Side.BUY, 10, 1_000));
            }
        }
    }

    /**
     * A fixed pseudo-random order flow, generated once per iteration before timing starts.
     *
     * <p>The stream is generated by running it against a scratch engine, so every cancel and
     * replace targets an order that really is resting at that point, and a simple controller
     * keeps the number of resting orders near {@link #TARGET_RESTING}. The measured engine
     * replays exactly the same sequence from an empty book, so it sees the same book. When the
     * stream is exhausted the measured book is rebuilt and the stream restarts.
     */
    @State(Scope.Thread)
    public static class Stream {
        static final int TARGET_RESTING = 2_000;

        OrderBook orderBook;
        MatchingEngine engine;

        // kind: 0 limit, 1 market, 2 cancel, 3 replace
        byte[] kind = new byte[STREAM_LENGTH];
        boolean[] buy = new boolean[STREAM_LENGTH];
        int[] quantity = new int[STREAM_LENGTH];
        long[] price = new long[STREAM_LENGTH];
        long[] target = new long[STREAM_LENGTH];                 // id to cancel/replace
        int position;
        long nextId;

        @Setup(Level.Iteration)
        public void setup() {
            generate();
            resetBook();
        }

        void resetBook() {
            orderBook = new OrderBook();
            engine = new MatchingEngine(orderBook);
            position = 0;
            nextId = 1;
        }

        private void generate() {
            OrderBook scratchBook = new OrderBook();
            MatchingEngine scratch = new MatchingEngine(scratchBook);
            Random random = new Random(42);
            java.util.ArrayList<Long> maybeResting = new java.util.ArrayList<>();
            long id = 1;

            for (int i = 0; i < STREAM_LENGTH; i++) {
                buy[i] = random.nextBoolean();
                quantity[i] = 1 + random.nextInt(50);
                int roll = random.nextInt(100);
                boolean overTarget = maybeResting.size() > TARGET_RESTING;
                kind[i] = (byte) (overTarget ? 2 : roll < 55 ? 0 : roll < 75 ? 1 : roll < 95 ? 2 : 3);

                // passive limits sit 1..10 ticks away from a fixed mid of 1000; 10% cross it
                long distance = 1 + random.nextInt(10);
                boolean aggressive = random.nextInt(10) == 0;
                price[i] = buy[i] ? (aggressive ? 1000 + distance : 1000 - distance)
                                  : (aggressive ? 1000 - distance : 1000 + distance);

                if ((kind[i] == 2 || kind[i] == 3)) {
                    long victim = takeResting(maybeResting, scratchBook, random, kind[i] == 3);
                    if (victim == 0) kind[i] = 1;                    // nothing to target: send a market order
                    else target[i] = victim;
                }

                switch (kind[i]) {
                    case 0 -> {
                        long newId = id++;
                        scratch.processOrder(new LimitOrder(newId, buy[i] ? Side.BUY : Side.SELL, quantity[i], price[i]));
                        if (scratchBook.hasOrder(newId)) maybeResting.add(newId);
                    }
                    case 1 -> scratch.processOrder(
                            new MarketOrder(id++, buy[i] ? Side.BUY : Side.SELL, quantity[i]));
                    case 2 -> scratch.cancelOrder(target[i]);
                    default -> scratch.replaceOrder(target[i], quantity[i], price[i]);
                }
            }
        }

        /** A random id that is still resting, or 0 if there is none. Dead ids are dropped on the way. */
        private static long takeResting(java.util.ArrayList<Long> candidates, OrderBook book, Random random,
                                        boolean keep) {
            while (!candidates.isEmpty()) {
                int index = random.nextInt(candidates.size());
                long candidate = candidates.get(index);
                if (!book.hasOrder(candidate)) {
                    candidates.set(index, candidates.get(candidates.size() - 1));
                    candidates.remove(candidates.size() - 1);
                    continue;
                }
                if (!keep) {                                         // a cancel removes it from the pool
                    candidates.set(index, candidates.get(candidates.size() - 1));
                    candidates.remove(candidates.size() - 1);
                }
                return candidate;
            }
            return 0;
        }
    }

    @Benchmark
    public void addThenCancel(SmallBook state) {
        long id = state.nextId++;
        state.engine.processOrder(new LimitOrder(id, Side.BUY, 10, 500));   // far from the market
        state.engine.cancelOrder(id);
    }

    @Benchmark
    public void restAndSweep(SmallBook state) {
        state.engine.processOrder(new LimitOrder(state.nextId++, Side.SELL, 10, 1_500));
        state.engine.processOrder(new MarketOrder(state.nextId++, Side.BUY, 10, TimeInForce.IOC));
    }

    @Benchmark
    public void cancelAndReaddInDeepLevel(DeepLevel state) {
        // full-period LCG (Hull-Dobell: c=1, a-1=7000 divisible by 2, 5 and 4): visits every id
        state.cursor = (int) ((state.cursor * 7001L + 1) % DEEP_LEVEL_ORDERS);
        long id = state.cursor;
        state.engine.cancelOrder(id);
        state.engine.processOrder(new LimitOrder(id, Side.BUY, 10, 1_000));
    }

    @Benchmark
    public ExecutionResult mixedStream(Stream state) {
        int i = state.position;
        if (i == STREAM_LENGTH) {                      // stream exhausted: rebuild the book, replay from the start
            state.resetBook();
            i = 0;
        }
        state.position = i + 1;
        Side side = state.buy[i] ? Side.BUY : Side.SELL;

        switch (state.kind[i]) {
            case 0:
                return state.engine.processOrder(
                        new LimitOrder(state.nextId++, side, state.quantity[i], state.price[i]));
            case 1:
                return state.engine.processOrder(
                        new MarketOrder(state.nextId++, side, state.quantity[i]));
            case 2:
                state.engine.cancelOrder(state.target[i]);
                return null;
            default:
                return state.engine.replaceOrder(state.target[i], state.quantity[i], state.price[i]);
        }
    }
}
